sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - ng build ngx-folder-uploader-lib

script:
  - ng build --prod --aot
